### ISSUE TITLE
D1.8.1 Technical Risk Assessment Document

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#18]
This is an issue of the task : T1.8	Technical Risk Assessment and Management (OBEO + UNIT + KOCSISTEM + ALL)
-------------------------------------------------------------------------------------------------------------

As ModelWriter brings a whole new approach, it is very important to determine all the technical risks on the achievement of this project.
This task is about assessing, from the user and software requirements, all the technical risks. For each of these risks, we will have to provide a way to control it, and if possible how could we propose an alternative solution if risk cannot be assessed. A typical example is to assess that semantically parsing a piece of text cannot be possible all the time. To control that risk, we will try to define constraints on the document (and for example specify its structure). We could then propose an alternative solution allowing to keep the ability to link this piece of text with an element of the Knowledge Base by providing a tooling allowing to drag a model element on this piece of text (a bit like what is done inside Intent.
This task will result in a Technical Risk Assessment Document (D1.8.1), created at the beginning of the project, updated throughout the project and with a special yearly review at the time of the software requirements and architecture review.

**Comment by mrostren** [comment]
email sent to ModelWriter consortium on 18th of May:
-----------------------------------------------------------------------------------------------------------
In order to complete the D1.8.1 Technical Risk Assessment please find attached the first draft which initiates the document.
I invite all technical partners to review, complete and comment this document.
Please do not forget to open track change utility before making your changes. 
-----------------------------------------------------------------------------------------------------------

**Comment by m-challenger** [comment]
- OBEO will push the final document into the github and close the deliverable.

**Comment by ylussaud** [comment]
The document is complete, I'm closing this issue
