### ISSUE TITLE
D1.3.2 Corpus for French Use Cases (Public)

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Deliverables#6]

**Comment by m-challenger** [comment]
Part of the corpus data is provided by the partners. However, some of the other partners have not decided on their corpus cases. 
Anyway, as some of the partners have not also decided for the privacy or publicity of the data, all of the corpus data is kept in a private repository in the GitHub.

@ModelWriter/consortium

**Comment by annemonceaux** [comment]
For what concerns Airbus Group FR4 and FR5 UCs
- All current text corpora – both SIDP documents and normalized rule database – are private.  Some excerpts of them can be used for public demo. I expect this private data not to be accessible from all partners since Airbus SAS provided them under NDA.
- The ontology,  i.e. the concepts part (Tbox),  is public (but not the dataset (populated knowledge base) since this KB actually contains the normalized rule DB content)
